import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import fetch from 'node-fetch'
import { access } from 'fs'
import { type } from 'os'
import shelter from './shelters/[id]'


const Home: NextPage<{ testdata: String, access_token: String }> = props => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>CatAdoption</h1>
        <p>Adopt a Cat Today!</p>
        <p>{String(props.testdata)}</p>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async ({
  params,
  res
}) => {
  const username = process.env.APP_USERNAME;
  const password = process.env.APP_PASSWORD;

  const result = await fetch('http://localhost:3033/auth/login', {
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/json',
    },
    method: 'POST',
    body: JSON.stringify({
      username: username,
      password: password
    })
  });

  type access_token_response = {
    access_token: string
  }

  const data = await result.json();
  let response: access_token_response = data;
  const token = response.access_token;
  console.log(response)

  const shelter_data = await fetch('http://localhost:3033/shelters', {
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/json',
      Authorization: "Bearer " + token
    },
    method: 'GET'
  });
  const shelter_json = await shelter_data.json();
  console.log(shelter_json);

  return {
    props: {
      testdata: "thisworks",
      shelters: shelter_json
    }
  };


}

export default Home
